/**
 * Closed set of stable error codes.
 * All codes must match /^[A-Z][A-Z0-9_]{1,119}$/
 */
export const ErrorCodes = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  DOMAIN_RULE_VIOLATION: "DOMAIN_RULE_VIOLATION",
  UNAVAILABLE: "UNAVAILABLE",
  UNEXPECTED_FAILURE: "UNEXPECTED_FAILURE",
  // Health / readiness
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  SCHEMA_NOT_READY: "SCHEMA_NOT_READY",
  // Config
  CONFIG_MISSING: "CONFIG_MISSING",
  CONFIG_INVALID: "CONFIG_INVALID",
  // Work
  WORK_HANDLER_NOT_REGISTERED: "WORK_HANDLER_NOT_REGISTERED",
  WORK_INVALID_SCOPE: "WORK_INVALID_SCOPE",
  WORK_INVALID_PAYLOAD: "WORK_INVALID_PAYLOAD",
  WORK_MAX_ATTEMPTS_EXCEEDED: "WORK_MAX_ATTEMPTS_EXCEEDED",
  WORK_UNEXPECTED_FAILURE: "WORK_UNEXPECTED_FAILURE",
  WORK_CANCELLED: "WORK_CANCELLED",
  // CORS
  CORS_ORIGIN_NOT_ALLOWED: "CORS_ORIGIN_NOT_ALLOWED",
  // Correlation
  CORRELATION_INVALID: "CORRELATION_INVALID",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
